"""add copy_allowed to assessments

Revision ID: ab5dc9d2faf4
Revises: f754d45f697f
Create Date: 2025-07-08 09:05:25.566415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5dc9d2faf4'
down_revision = 'f754d45f697f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('copy_allowed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('copy_allowed')

    # ### end Alembic commands ###
